## o poblema das n-rainhas
O problema da n-rainhas consiste em organizar n-rainhas em um tabuleiro n x n de uma forma em que as rainhas não se matem.

Exemplo: 5-rainhas, tabuleiro 5x5

|   | A | B | C | D | E |   |
|---|---|---|---|---|---|---|
| 1 | ♛ |   |   |   |   | 1 |
| 2 |   |   | ♛ |   |   | 2 |
| 3 |   |   |   |   | ♛ | 3 |
| 4 |   | ♛ |   |   |   | 4 |
| 5 |   |   |   | ♛ |   | 5 |
|   | A | B | C | D | E |   |

## Algoritmo: Genético
O algoritmo genético consite em uma forma de selecionar as melhores soluções em com
base na genética através de um cruzamento utilizando uma função de avalição para selecionar os melhores indivíduos de suas respectivas gerações.

1. Os primeiros indíviduos (população) serão gerados aleatoriamente
2. Será realziado o fitness avaliando os melhores indivíduos (função de avaliação)
3. Sera realizado a seleção dos indivíduos com o melhor grau de avaliação
4. Mutação e Cruzamento para gerar uma nova geração de indivíduo
5. Passar pelo critério de parada, se a solução ainda não é satisfatória execute os passos novamente.

![Fluxo algoritmo genético](https://computacaointeligente.com.br/assets/img/posts/GA/fluxograma.png)

# Modelagem do problema
Cada indivíduo será um tabuleiro preenchido com 1 e 0 referente a posição de cada rainha e espaços em brancos

### Exemplo: indivíduo 1:
[[0, 0, 0 , 1, 0],
[0, 0, 0 , 0, 1],
[0, 0, 1 , 0, 0],
[0, 0, 0 , 0, 1],
[0, 0, 0 , 0, 1]]

|   | A | B | C | D | E |   |
|---|---|---|---|---|---|---|
| 1 |   |   |   | ♛ |   | 1 |
| 2 |   |   |   |   | ♛ | 2 |
| 3 |   |   | ♛ |   |   | 3 |
| 4 |   |   |   |   | ♛ | 4 |
| 5 |   |   |   |   | ♛ | 5 |
|   | A | B | C | D | E |   |

### Exemplo: indivíduo 2:

[[0, 0, 1 , 0, 0],
[0, 0, 0 , 0, 1],
[1, 0, 0 , 0, 0],
[0, 1, 0 , 0, 0],
[0, 0, 1 , 0, 0]]

|   | A | B | C | D | E |   |
|---|---|---|---|---|---|---|
| 1 |   |   | ♛ |   |   | 1 |
| 2 |   |   |   |   | ♛ | 2 |
| 3 | ♛ |   |   |   |   | 3 |
| 4 |   | ♛ |   |   |   | 4 |
| 5 |   |   | ♛ |   | ♛ | 5 |
|   | A | B | C | D | E |   |


### Exemplo: cruzamento
[[0, 0, 0 , 1, 0],
[0, 0, 0 , 0, 1],
[1, 0, 0 , 0, 0],
[0, 1, 0 , 0, 0],
[0, 0, 1 , 0, 0]]


|   | A | B | C | D | E |   |
|---|---|---|---|---|---|---|
| 1 |   |   |   | ♛ |   | 1 |
| 2 |   |   |   |   | ♛ | 2 |
| 3 | ♛ |   |   |   |   | 3 |
| 4 |   | ♛ |   |   |   | 4 |
| 5 |   |   | ♛ |   |   | 5 |
|   | A | B | C | D | E |   |


In [2]:
import numpy as np
from random import randint
N = 5
qnt=10
def gerarIndividuo(n):
    individuo = np.zeros((n, n))
    lastGenerated=[]
    lastGenerated2=[]
    for i in range(n):
        randPos = [np.random.randint((n, n)) for x in range(n)]
        randPos2 = [np.random.randint((n, n)) for x in range(n)]
        while [randPos[i][1]] in lastGenerated and [randPos[i][0]] in lastGenerated2:
            randPos = [np.random.randint((n, n)) for x in range(n)]
        lastGenerated2.append(randPos[i][0])
        lastGenerated.append(randPos[i][1])
    for i in range(n):
        individuo[lastGenerated2[i]][lastGenerated[i]] = 1
    return individuo

def gerarPopulacao(qnt):
    populacao = []
    for i in range(qnt):
        individuo=gerarIndividuo(N)
        populacao.append(individuo)
    return np.array(populacao)
populacao = gerarPopulacao(qnt)
print(populacao)

[[[0. 0. 0. 0. 0.]
  [0. 1. 1. 0. 0.]
  [1. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 1.]
  [1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 1. 0. 0. 0.]]

 [[0. 1. 0. 0. 0.]
  [1. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 1. 1. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [1. 1. 0. 0. 1.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 0. 1. 0. 1.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1.]
  [0. 1. 0. 0. 0.]]

 [[0. 0. 0. 1. 1.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0.]]

 [[0. 0. 0. 1. 0.]
  [1. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [1. 0. 0. 0. 0.]]

 [[1. 1. 0. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1.]]

 [[0. 0. 1. 0. 0.]
  [0. 1. 1. 1. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[1. 0. 0. 1. 0.]
  [0. 0. 1. 0. 0.]
  [1. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [15]:
def avaliar(populacao):
    posicoes=[[] for x in range(len(populacao))]
    count=0
    # Pergar as posicções das rainhas
    for individuo in populacao:
        for i in range(len(individuo)):
            for j in range(len(individuo)):
                if individuo[i][j] == 1:
                    posicoes[count].append([i, j])
        count=count+1
    count=0
    max=[]
    for i in range(len(posicoes)):
        linha_pos=[[] for x in range(len(posicoes))]
        coluna_pos=[[] for x in range(len(posicoes))]
        pontos_linhas=0
        pontos_coluna=0
        pontos_diagonais=0
        for j in range(N):
            # linha
            pos_linha=posicoes[i][j][0]
            if pos_linha not in linha_pos[i]:
                linha_pos[i].append(pos_linha)
            else:
                pontos_linhas+=1
            # coluna
            pos_coluna=posicoes[i][j][1]
            if pos_coluna not in coluna_pos[i]:
                coluna_pos[i].append(pos_coluna)
            else:
                    pontos_coluna+=1
            # diagonais
            currentPosL = posicoes[i][j][0]
            currentPosC = posicoes[i][j][1]
            for k in range(N):
                if currentPosL == 0 and currentPosC == 0: continue
                lastPosL = posicoes[i][k][0]
                lastPosC = posicoes[i][k][1]
                #if currentPosL != 0 and currentPosC != 0 and lastPosL != 0 and lastPosC != 0:
                distL = (int(currentPosL+1) % int(lastPosL+1))
                distC = (int(currentPosC+1) % int(lastPosC+1))
                if distC == distL:
                    pontos_diagonais += 1
        max.append(pontos_diagonais+pontos_linhas+pontos_coluna)
    return max

    
avaliados = avaliar(populacao)
print(avaliados)

[12, 10, 11, 16, 11, 12, 12, 14, 15, 14]


In [4]:
def cross(a, b):
    individuo_a = populacao[a]
    individuo_b = populacao[b]

    # quantidade de linhas
    linhas_qnt = int((len(individuo_a) / 2 + len(individuo_b) / 2) / 2)

    # linhas que vão cruzar
    linhas_a = []
    linhas_b = []

    # sorteando linhas que vão cruzar
    for x in range(linhas_qnt):
        linhas_a.append(randint(0, (len(individuo_a)-1)))
        linhas_b.append(randint(0, (len(individuo_b)-1)))

    # cruzamento
    linha_size = len(linhas_a)
    for i in range(linha_size):
        swap_a = np.copy( individuo_a[linhas_a[i]])
        swap_b = np.copy(individuo_b[linhas_b[i]])
        individuo_a[linhas_a[i]] = swap_b
        individuo_b[linhas_b[i]] = swap_a
    
    populacao[a] = individuo_a
    populacao[b] = individuo_a


0
